from __future__ import annotations

from pcr_audit.product.common import (
    CODE_SUFFIXES,
    DATA_SUFFIXES,
    DOC_SUFFIXES,
    IMAGE_SUFFIXES,
    MATERIAL_ROLES,
    SYSTEM_DIR_NAMES,
    SYSTEM_FILE_NAMES,
    AuditConfig,
    Material,
    ProjectSpec,
    _cached_lookup,
    _cache_key,
    _env_config,
    _external_enabled,
    _grobid_endpoint,
    _http_json,
    _now_iso,
    extract_text_with_grobid,
    finding,
    is_audit_material_path,
    iter_audit_files,
)
from pcr_audit.product.reference_audit import (
    _extract_reference_text,
    analyze_citation_claims,
    analyze_papermill_signals,
    analyze_references,
)
from pcr_audit.product.image_audit import (
    _average_hash,
    _copy_move_matches,
    _difference_hash,
    _hamming,
    _hash_summary,
    _image_metadata_findings,
    _orb_similarity,
    _perceptual_hash,
    _phash_from_array,
    _pil_image_module,
    _transformed_phash_distances,
    analyze_images,
    extract_docx_images,
    extract_pdf_images,
    image_fingerprints,
    iter_image_files,
)
from pcr_audit.product.provenance import (
    _file_metadata,
    _latest_ledger_records,
    _project_paths_for_provenance,
    _read_ledger,
    _relative_to_project,
    _sha256_file,
    analyze_provenance,
    analyze_provenance_paths,
    default_ledger_path,
    provenance_diff,
    provenance_init,
    provenance_payload_to_result,
    provenance_record,
    provenance_verify,
)
from pcr_audit.product.code_audit import analyze_code_files
from pcr_audit.product.project_manifest import (
    infer_role,
    init_manifest_payload,
    inspect_project_payload,
    parse_project_spec,
    payload_from_results,
    project_sources,
    role_summary,
)
from pcr_audit.product.corpus_signals import (
    _corpus_project_paths,
    _extract_metadata_from_text,
    _hex_hamming,
    _image_index_entries,
    _jaccard,
    _project_texts,
    _shingles,
    _simhash,
    _tokens,
    analyze_papermill_network_signals,
    build_corpus_index,
    project_corpus_features,
)

__all__ = [name for name in globals() if not name.startswith("__")]
